# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 2
from nbdev.showdoc import *
from fastcore.test import *
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 3
suits = ["♣️","♠️","♥️","♦️"]
ranks = [None,"A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb 12
class Card:
    "A playing card created by passing a `suit` from `suits` and `rank` from `ranks`"
    def __init__(self,
                 suit:int, # An index into `suits`
                 rank:int): # An index into `rank`
        self.suit,self.rank = suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__

# %% ../nbs/00_card.ipynb 17
@patch
def __eq__(self:Card, a:Card): return (self.suit,self.rank)==(a.suit,a.rank)
@patch
def __gt__(self:Card, a:Card): return (self.suit,self.rank)>(a.suit,a.rank)
@patch
def __lt__(self:Card, a:Card): return (self.suit,self.rank)<(a.suit,a.rank)
